In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 1.6 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.8 MB 1.6 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/12.8 MB 1.3 MB/s eta 0:00:09
   ---- ----------------------------------- 1.6/12.8 MB 1.4 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.8 MB 1.6 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.8 MB 1.6 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.8 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.8 MB 1.7 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.8 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 3.9/12.8 MB 1.7 MB/s eta 0:00:06
   ------------- ---


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [43]:
import numpy as np  


In [44]:
np.__version__  #2 underscores

'2.1.3'

In [5]:
my_list = [0,1, 2, 3, 4, 5]   
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)   

list

In [7]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(type(arr))  # <class 'numpy.ndarray'> mutipal array and 3D array

<class 'numpy.ndarray'>


In [9]:
np.arange( 10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange( 10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(20,10)#  also the 1st argument is greater than the 2nd, so it returns an empty array 

array([], dtype=int64)

In [12]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [ ]:
np.zeros(5)  # 1D array of zeros
# this is called parameter tunning

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, dtype=int)  # 1D array of zeros
# this is called hyperparameter tuning (changing the dtype)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros([2,2])  # 2D array of zeros

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros([2,2], dtype=int)  # 2D array of zeros with integer type

array([[0, 0],
       [0, 0]])

In [ ]:
np.zeros([5,4],dtype=int)  # ndarray means greater than 3 array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
#np.array([3,4])
# 3 --- means always be row
# 4 --- means always be column

In [ ]:
np.zeros((10,10), dtype=int) # ndarray means greater than 3 array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones((2), dtype=int)  

array([1, 1])

In [24]:
np.ones((4,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
rand(3,2)

NameError: name 'rand' is not defined

In [26]:
random.rand(3,2)

NameError: name 'random' is not defined

In [30]:
np.random.rand(3,2)

array([[0.28766668, 0.87908615],
       [0.51726067, 0.19125348],
       [0.74106814, 0.30732732]])

In [31]:
np.random.rand(3)

array([0.80170452, 0.56738526, 0.46358196])

In [45]:
np.random.randint(0,10)

3

In [46]:
np.random.randint(0,10,3)

array([4, 2, 2], dtype=int32)

In [51]:
np.random.randint(0,50,5)

array([33, 49,  9, 35,  1], dtype=int32)

In [42]:
n = np.random.randint(10,40,(8,10))
print(n)

[[15 38 29 34 32 10 30 33 35 20]
 [33 21 21 39 14 31 30 27 39 24]
 [12 20 27 35 22 28 10 27 16 19]
 [23 13 37 25 29 30 15 24 13 37]
 [15 15 22 18 36 29 11 38 20 29]
 [22 34 31 31 14 12 31 25 38 13]
 [11 14 39 32 30 36 29 17 31 28]
 [10 38 19 38 29 38 28 39 37 34]]


In [41]:
print(n[0]) #row print

[27 24 35 36 38 17 31 39 32 18]


In [40]:
print(n[5]) #row print

[10 39 28 26 15 36 28 21 30 21]


In [39]:
print(n[0:6]) # 1 to 5 row print

[[27 24 35 36 38 17 31 39 32 18]
 [28 17 38 34 14 13 35 36 24 16]
 [35 23 17 20 23 12 16 16 37 20]
 [12 12 27 20 37 25 16 12 26 16]
 [37 34 27 26 19 21 12 37 36 35]
 [10 39 28 26 15 36 28 21 30 21]]


In [38]:
print(n)

[[27 24 35 36 38 17 31 39 32 18]
 [28 17 38 34 14 13 35 36 24 16]
 [35 23 17 20 23 12 16 16 37 20]
 [12 12 27 20 37 25 16 12 26 16]
 [37 34 27 26 19 21 12 37 36 35]
 [10 39 28 26 15 36 28 21 30 21]
 [30 24 37 37 17 29 35 10 27 39]
 [11 30 38 26 35 25 21 21 39 34]]


In [37]:
print(n[::-1])  # all reverse row print and called backward indexing

[[11 30 38 26 35 25 21 21 39 34]
 [30 24 37 37 17 29 35 10 27 39]
 [10 39 28 26 15 36 28 21 30 21]
 [37 34 27 26 19 21 12 37 36 35]
 [12 12 27 20 37 25 16 12 26 16]
 [35 23 17 20 23 12 16 16 37 20]
 [28 17 38 34 14 13 35 36 24 16]
 [27 24 35 36 38 17 31 39 32 18]]


In [36]:
print(n[::1]) # called forward indexing is equal to variable (n)

[[27 24 35 36 38 17 31 39 32 18]
 [28 17 38 34 14 13 35 36 24 16]
 [35 23 17 20 23 12 16 16 37 20]
 [12 12 27 20 37 25 16 12 26 16]
 [37 34 27 26 19 21 12 37 36 35]
 [10 39 28 26 15 36 28 21 30 21]
 [30 24 37 37 17 29 35 10 27 39]
 [11 30 38 26 35 25 21 21 39 34]]


In [35]:
print(n[::2]) # 0 row is print and 1 row is delet then 2 row is perint and 3s is delet and so on

[[27 24 35 36 38 17 31 39 32 18]
 [35 23 17 20 23 12 16 16 37 20]
 [37 34 27 26 19 21 12 37 36 35]
 [30 24 37 37 17 29 35 10 27 39]]


In [34]:
print(n[0:5]) # zero row and 5 col

[[27 24 35 36 38 17 31 39 32 18]
 [28 17 38 34 14 13 35 36 24 16]
 [35 23 17 20 23 12 16 16 37 20]
 [12 12 27 20 37 25 16 12 26 16]
 [37 34 27 26 19 21 12 37 36 35]]


In [33]:
print(n[0,5])

17


In [32]:
print(n)

[[27 24 35 36 38 17 31 39 32 18]
 [28 17 38 34 14 13 35 36 24 16]
 [35 23 17 20 23 12 16 16 37 20]
 [12 12 27 20 37 25 16 12 26 16]
 [37 34 27 26 19 21 12 37 36 35]
 [10 39 28 26 15 36 28 21 30 21]
 [30 24 37 37 17 29 35 10 27 39]
 [11 30 38 26 35 25 21 21 39 34]]


In [31]:
print(n[5,3]) #5 rows, 3 columns

26


In [30]:
print(n[5,-3])#5 rows, -3  reverse columns

21


In [ ]:
# : in matrix record
# , in matrix specific position (element)

In [25]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [27]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [29]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])